fix "Start up error #1" issue
Previous error message is given below
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.62 (77dd1dc1) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-05-11 02:11:00

Caught exception:
Traceback (most recent call last):
File "C:\Users\User\AppData\Roaming\Anki2\addons21\461193445\main.py", line 17, in create_multiple_decks
info = show_custom_dialog()
File "C:\Users\User\AppData\Roaming\Anki2\addons21\461193445\main.py", line 10, in show_custom_dialog
dialog = my_user_interactive_GUI.MyCustomDialog(mw)
File "C:\Users\User\AppData\Roaming\Anki2\addons21\461193445\src\my_user_interactive_GUI.py", line 176, in init
file_widget = FileWidget()
File "C:\Users\User\AppData\Roaming\Anki2\addons21\461193445\src\my_user_interactive_GUI.py", line 41, in init
self.file_list.setSelectionMode(QListWidget.ExtendedSelection)
AttributeError: type object 'QListWidget' has no attribute 'ExtendedSelection'
```